In [1]:
import pandas as pd

In [2]:
states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 
          'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 
          'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 
          'VA', 'WA', 'WV', 'WI', 'WY']

In [26]:
df = pd.read_csv(r'../data/03-14_lstm_msn.csv', header=None)
df.shape

(20, 1520)

In [27]:
to_drop = []

for i in range(1, df.shape[1]):
    if df.iloc[0, i] not in states:
        to_drop.append(i)

df.drop(labels=to_drop, axis=1, inplace=True)

In [28]:
df

,0,1,2,3,4,5,6,7,8,9,...,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508
0,Year,AK,AK,AK,AK,AK,AK,AK,AK,AK,...,WY,WY,WY,WY,WY,WY,WY,WY,WY,WY
1,NaN,BDFDB,BDPRP,BFFDB,BFPRP,CLPRB,CLPRK,CLPRP,COPRK,EMFDB,...,REPRB,SOTCB,TEPRB,TETCB,WDEXB,WDPRB,WDTCB,WSTCB,WWPRB,WYTCB
2,2003,0,0,0,0,16864,15.6,1081,5.8,0,...,12064,2,8585257,461215,0,875,875,13,888,3711
3,2004,0,0,0,0,23587,15.6,1512,5.8,0,...,14434,2,8996981,450647,0,898,898,13,911,6175
4,2005,0,0,0,0,22682,15.6,1454,5.8,0,...,19105,3,9151117,456839,0,2433,2433,13,2446,7172
5,2006,0,0,0,0,22230,15.6,1425,5.8,0,...,19351,4,10057248,478077,0,2102,2102,0,2102,7529
6,2007,0,0,0,0,20654,15.6,1324,5.8,0,...,18322,4,10411137,523640,0,2305,2305,0,2305,7461
7,2008,0,0,0,0,23041,15.6,1477,5.8,0,...,21703,5,10879840,538379,0,2545,2545,0,2545,9485
8,2009,0,0,0,0,29016,15.6,1860,5.8,0,...,34009,4,10328914,524122,0,1360,1360,0,1360,21728
9,2010,0,0,0,0,33556,15.6,2151,5.8,0,...,44768,6,10528548,541026,0,1492,1492,0,1492,31676
10,2011,0,0,0,0,33524,15.6,2149,5.8,0,...,60357,6,10343561,557822,0,1434,1434,2,1436,44809
11,2012,0,0,0,0,31332,15.268,2052,5.8,0,...,53776,15,9603286,551037,0,1222,1222,2,1225,41576
12,2013,0,0,0,0,24917,15.272,1632,5.8,0,...,53125,24,9232597,539997,0,1542,1542,2,1544,42298
13,2014,0,0,0,0,22944,15.278,1502,5.8,0,...,54146,24,9358194,536312,0,1567,1567,2,1569,41899
14,2015,21,4,21,4,17747,15.073,1177,5.717,0,...,49887,27,9080777,507121,0,4904,4904,2,4905,35009
15,2016,27,5,27,5,13942,14.957,932,5.722,0,...,54565,33,7518440,504984,0,4357,4357,2,4358,40522
16,2017,29,5,29,5,14365,14.978,959,5.723,0,...,55916,45,7794586,534840,0,5049,5049,0,5049,39806
17,2018,15,3,15,3,13752,15.253,902,5.706,0,...,51483,67,7711992,557604,0,4934,4934,0,4934,36936
18,2019,0,0,0,0,14867,15.252,975,5.698,0,...,53228,1688,7148285,546671,0,4969,4969,0,4969,37070
19,2020,0,0,0,0,15523,15.206,1021,5.691,0,...,64877,1566,5884410,504390,0,4757,4757,0,4757,48362

In [29]:
df.to_csv(r'../data/03-14_lstm_msn.csv')