In [1]:
import pandas as pd

In [4]:
pd.read_csv(r'../data/transformed_data.csv')

,StateCode,Year,CO2 Emissions (Mmt),TotalNumberofInvestments,TotalAmountofAssistance,BDFDB,BDPRP,BFFDB,BFPRP,CLPRB,...,REPRB,SOTCB,TEPRB,TETCB,WDEXB,WDPRB,WDTCB,WSTCB,WWPRB,WYTCB
0,AK,2015,35.027804,16.0,3345612.0,21.0,4.0,21.0,4.0,17747.0,...,23807.0,3.0,1429942,614242.0,0.0,6865.0,6865.0,622.0,7488.0,1488.0
1,AK,2016,33.405611,14.0,2247734.0,27.0,5.0,27.0,5.0,13942.0,...,25155.0,14.0,1435363,593662.0,0.0,7636.0,7636.0,412.0,8048.0,1563.0
2,AK,2017,33.729130,18.0,13509662.0,29.0,5.0,29.0,5.0,14365.0,...,23620.0,20.0,1454196,601492.0,0.0,6501.0,6501.0,436.0,6937.0,1305.0
3,AK,2018,34.514589,44.0,18236626.0,15.0,3.0,15.0,3.0,13752.0,...,24158.0,28.0,1410604,604644.0,0.0,6910.0,6910.0,456.0,7366.0,1411.0
4,AK,2019,34.259440,32.0,13734021.0,0.0,0.0,0.0,0.0,14867.0,...,22754.0,40.0,1370342,605689.0,0.0,6418.0,6418.0,386.0,6803.0,1270.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,X3,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,4788597,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,X5,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,65465,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,X5,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,35156,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,X5,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,32701,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,X5,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27811,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
x = [1, 2, 3]
x[1: -1]

[2]